### PR TITLE
land: update build_fingerprint

### PR DESCRIPTION
**Pull request by dasshubham762**
Latest MIUI 8.5.4.0.MALMIED

### CODE REVIEW

**Comment by arizaini** [comment]
8.5.4.0 is not released yet to public, so better to stay with the final release global stable (8.5.3.0)

**Comment by dasshubham762** [comment]
Okay. It will be released in public within few days. Then change the fingerprint. 🙂

**Comment by dasshubham762** [comment]
Update has released publically.

**Comment by Klozz** [comment]
can you link me I want to download it :D

**Comment by dasshubham762** [comment]
Here it is
http://bigota.d.miui.com/V8.5.4.0.MALMIED/miui_HM3SGlobal_V8.5.4.0.MALMIED_b2ff7423f6_6.0.zip

**Comment by dasshubham762** [comment]
http://en.miui.com/download-303.html

**Comment by Klozz** [comment]
thanks

**Comment by dasshubham762** [comment]
You're always welcome sir.

**Pull request merged**
