### PR TITLE
gps: remove slim_daemon

### PR DESCRIPTION
**Pull request by ygorigor**
It's a PREMIUM_FEATURE daemon and it's causing errors on O.

01-29 01:03:28.327   877   877 F DEBUG   : Abort message: 'CANNOT LINK EXECUTABLE "slim_daemon": cannot locate symbol "_ZN7android16SensorEventQueue4readEP12ASensorEventm" referenced by "/system/vendor/bin/slim_daemon"...'

Change-Id: Iba1342d12b10e94be9e37724795a922996d32773

### CODE REVIEW

**Comment by nichcream** [comment]
Strange, I'm not getting these crashes and using the same libshims as Klozz.
Anyway, a better fix would be to entirely kang these GPS blobs from upstream (like OnePlus 3) IMO.

**Comment by ygorigor** [comment]
it because you don't have slim_daemon in izat.conf
look at original commit https://github.com/AOSiP/device_oneplus_oneplus3/commit/ee9c4423bbd2313abe6ecf2c5e18a6bc66521aac

**Comment by ygorigor** [comment]
I wanted to do a pull request to vendor tree, but it not contain last changes

**Comment by nichcream** [comment]
https://github.com/RainbowUnicornXPe/proprietary_vendor_xiaomi/commit/c6d3f26db5bb15a4cce07ae3c8cb7fa5491b0104#diff-4b08d60be4ea962a508eafb16e3e4125

Hmm...

**Comment by ygorigor** [comment]
The izat.conf from latest ROM contains this strings, so they was added back

**Pull request closed without merging**
