### PR TITLE
Fixed the flac format playback issue

### PR DESCRIPTION
**Pull request by zhongab1708**
Fixed the flac format playback issue, remove the wrong tag "OMX.qti.audio.decoder.flac" in meida_codecs.xml. This issue is show all Nougat rom for land, it test OK in RR Nougat

### CODE REVIEW

**Comment by Klozz** [comment]
It looks good to me, added.
Thanks.

**Comment by zhongab1708** [comment]
Please merge the translate for CMParts

**Comment by Klozz** [comment]
can u send your translations via crowding? I merged your translations but make issues when is compiled the xml

**Comment by zhongab1708** [comment]
OK, I will do it

**Pull request merged**
